#!/bin/bash

if [[ ${#@} < 1 ]]; then
    echo Expected argument: a number from 1 through 25
    exit 1
fi

problem_number=$1
shift

for suffix in "" "_2" "_test"; do
    f=day$problem_number$suffix.py
    if [[ -z "$suffix" || -f "$f" ]]; then
        echo "    *** $f: ***"
        cat "../inputs/$problem_number" | pypy3 "$f" "$@" || exit 1
    fi
done
