#!/bin/bash

if [[ ${#@} != 1 ]]; then
    echo Expected argument: a number from 1 to 25
    exit 1
fi

problem_number=$1
shift

for f in day$problem_number*.py; do
    echo '    ***' $f: '***'
    cat "../inputs/$problem_number" | pypy3 "$f" "$@"
done
