#!/bin/bash

if [[ ${#@} > 1 ]]; then
    echo Expected at most one argument: a number from 1 to 25
elif [[ ${#@} == 1 ]]; then
    problem_number=$1
else
    problem_number=25
fi

# Intcode computer tests
for f in cpu/intcode_computer.py cpu/test_intcode_computer.py; do
    echo "    *** $f: ***"
    pypy3 "$f" || exit 1
done

# Daily problems
for i in $(seq 1 $problem_number); do
    ./run $i || exit 1
done
