#!/bin/bash

if [[ ${#@} > 1 ]]; then
    echo Expected at most one argument: a number from 0 through 25
elif [[ ${#@} == 1 ]]; then
    problem_number=$1
else
    problem_number=25
fi

# Intcode computer tests
cd cpu
for f in intcode_computer.py test_intcode_computer.py; do
    echo "    *** $f: ***"
    mypy "$f" || exit 1
    pypy3 "$f" || exit 1
done
cd - >/dev/null

# Daily problems
for i in $(seq 1 $problem_number); do
    ./run $i || exit 1
done
