[package]
name = "day-7"
version = "0.1.0"
authors = ["Kevan Hollbach <khollbach@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu = { path = "../cpu" }
rayon = "1.3.1"
factorial = "0.2.0"
