#!/bin/bash

if [[ ${#@} != 1 ]]; then
    echo Expected exactly 1 argument: a number from 1 to 25
    exit 1
fi

problem_number=$1
shift
cat "../inputs/$problem_number" | pypy3 "$problem_number.py" "$@"

if [[ -f "$problem_number-2.py" ]]; then
    cat "../inputs/$problem_number" | pypy3 "$problem_number-2.py" "$@"
fi
