[package]
name = "day-6"
version = "0.1.0"
authors = ["Kevan Hollbach <khollbach@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
by_address = "1.0.4"
